### ISSUE TITLE
Unable to generate context files: Value cannot be null

### ISSUE THREAD

**Issue by altmank** [delegateas/XrmContext#11]
Hello,

Running the XrmContext.exe using an XrmContext.exe.config as follows results in the error "Unable to generate context files: Value cannot be null". 

I was unable to get the tool to connect to my on-prem 8.2 instance using the parameters due to "Parameter name: serviceConfiguration.CurrentServiceEndpoint" error, so I downloaded the metadata directly into JSON file from {baseurl}/api/data/v8.2/EntityDefinitions and referenced it in the below config. 

I'm stumped on what value is null as the error is not descriptive.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings file="EnvInfo.config">
    <add key="load" value="../../Metadata.json" />
    <add key="entities" value="account,contact" />
    <add key="ns" value="Context" />
    <add key="is" value="Customer:account;contact" />
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.3.0" newVersion="4.4.3.0" />
        <bindingRedirect oldVersion="2.3.5.0" newVersion="4.3.0.0" />
        <bindingRedirect oldVersion="4.0.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>`

**Comment by altmank** [comment]
Accidentally closed issue.

**Comment by Tolini** [comment]
The json suplied from EntityDefinitions has the wrong format for loading into XrmContext.
The load function is meant as a way to load a file previously saved by XrmContext to avoid doing unnessecary network calls when the system hasn't changed.

**Comment by TomMalow** [comment]
How have you installed XrmContext? Are you suing the Nuget package or cloned the proejct? You are using the XrmContext appconfig for the project which is not used to generate the context instead of the provided config that is part of the Nuget package.

**Comment by henrikhannemose** [comment]
I am closing this issue. Feel free to re-open and reply to @TomMalow's questions if your issue was not resolved.
