### ISSUE TITLE
Warnings in XrmContext.cs (CS1591)

### ISSUE THREAD

**Issue by jynxeh** [delegateas/XrmContext#15]
Hi,

The generated XrmContext and the XrmExtensions both have violations for CS1591 (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591). This causes our quality gates to fail.

Currently, we have to manually add a line at the top to disable these warnings for the file:
#pragma warning disable 1591

I believe the 3 potential options to resolve this are:
1. Add the line to the file template
2. Resolve the warnings in the file (which would require generating comments and increasing the size of the file)
3. Add a setting to allow the user to define a file header to use for the generated file, they could then choose to add this if they wished.

I'd create a PR for this but I'm afraid my F# is extremely weak.

Thanks.

**Comment by magesoe** [comment]
I think we should just fix the warning, instead of allowing you to disable it. Those files are generated, which to me means that you should not modify them. This example has not convinced me that we should allow you to inject code, but the warnings should be fixed.

**Comment by bo-stig-christensen** [comment]
@jynxeh : I know this is an old issue and I am not sure if you still use XrmContext or have the issue.

I have verified that no warnings are present across several larger projects, so I assume that the issue has been mitigated as part of a subsequent build.

I'll close this issue for now. If you still have the issue, please feel free to reopen :-)

**Comment by jynxeh** [comment]
@bo-stig-christensen - yes we are still very actively using XrmContext in all of our projects, thank you. This issue is still present so an example would be:

        [AttributeLogicalName("activitypartyid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("activitypartyid", value);
            }
        }

To comply it would need to be generated with a comment, such as:

        /// <summary>
        /// Gets or sets the Id Guid
        /// </summary>
        [AttributeLogicalName("activitypartyid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("activitypartyid", value);
            }
        }

It would be extremely useful if the comments generated were also StyleCop compliant, otherwise it will just move the issue for us and potentially other users. This will also need to be added to all enums and other elements with public scope.

Let me know your thoughts.
