### ISSUE TITLE
Strongly Typed retrieve of entity does not handle .id attribute correctly

### ISSUE THREAD

**Issue by TomMalow** [delegateas/XrmContext#22]
As dicussed in issue https://github.com/delegateas/XrmMockup/issues/70, the strongly typed retrieve of an entity records with the attribute `.id` result in an invalid underlying retrieve call:
```csharp
var account = Account.Retrieve(orgAdminService, "Some_Account_Id", x => x.Id)
```
results in a similar call as
```csharp
var account = orgAdminService.Retrieve("account", "Some_Account_Id", new ColumnSet("id"));
```
But should have been 
```csharp
var account = orgAdminService.Retrieve("account", "Some_Account_Id", new ColumnSet("accountid"));
```

**Comment by robertraaijmakers** [comment]
Was checking my own comments and open issues. I think this issue can be closed? The solution was implemented in september 2019.

**Comment by misoeli** [comment]
As mentioned, implemented a while ago. Closing here.
