### ISSUE TITLE
Compatibility with .NET Core

### ISSUE THREAD

**Issue by Kuroiyatsu** [delegateas/XrmContext#24]
Is there any plan to get this library functioning with .NET Core? 

I run into System.ServiceModel exceptions. This is even when using System.ServiceModel.Primitives.

Thanks,

**Comment by misoeli** [comment]
For future reference, this can be done as described here: https://github.com/delegateas/XrmContext/wiki/Using-XrmContext-in-a-.net-core-project.

Closing here.
