### ISSUE TITLE
Cannot convert from 'Account' to 'Microsoft.Xrm.Sdk.Entity'

### ISSUE THREAD

**Issue by obkirneh** [delegateas/XrmContext#26]
Hi,

I'm trying out XrmContext and are experience an odd behavior that I can't figure out.
If I generate early-bound .NET classes with a config where I either specify a solution or entities then all works fine.
Here is a sample of my config:
```  
<appSettings>
    <add key="url" value="https://instance.crm4.dynamics.com/XRMServices/2011/Organization.svc" />
    <add key="username" value="x@y.z" />
    <add key="password" value="pwd" />
    <add key="solutions" value="" />
    <add key="entities" value="account"/>
    <add key="servicecontextname" value="Xrm" />
    <add key="out" value="..\Model"/>
</appSettings>
```

Code:
```
var acct = new Account()
      {
          Name = "XrmContext Test"
      };
 var aId = _orgService.Create(acct);
```

If I ommit the solutions and entities in the config and generate early-bound .NET classes for all entities I get the following error on `_orgService.Create(acct);`

`Error	CS1503	Argument 1: cannot convert from 'Account' to 'Microsoft.Xrm.Sdk.Entity'	`

Hope you can guide me in the right direction.

Kind regards,
Henrik

PS: XrmContext installed by Nuget.

**Environment**
- D365 version: 9.1.0.9033
- XrmContext version: 1.6.0
- Visual Studio version: 2019

**Comment by obkirneh** [comment]
Hi Magnus, 
You're probably right that either a solution or entities will be specified.
I was just playing around with XrmContext to get familiar with it... :)

**Comment by magesoe** [comment]
There are some f'ed up entities in D365. Some of them have illegal metadata, which means our tooling breaks
