### ISSUE TITLE
The type or namespace name 'OptionSetValueCollection' could not be found

### ISSUE THREAD

**Issue by plantoschka** [delegateas/XrmContext#30]
We're still using Dynamics 365 v8.2 (onPrem) and I receive this error when upgrading to the newest XrmContext NuGetPackage (v1.7.1).

I think OptionSetValueCollection is a new feature in v9.

Is it still possible to use a newer version of XrmContext in a v8 enviroment?

**Comment by magesoe** [comment]
You're correct. We never created different versions of XrmContext for different SDK's, like we did for XrmMockup. It is not a high priority for us to support older versions, since Microsoft has been, and still is, pushing for everyone to get on cloud and one version.

**Comment by misoeli** [comment]
Fixed in 3.0.
