### ISSUE TITLE
Error in DisplayName values OptionSetMetadata 

### ISSUE THREAD

**Issue by pksorensen** [delegateas/XrmContext#42]
Tror jeg har fundet en fejl i displayName værdierne i OptionSetMetadata Attributen. Her 2 eksempler:

Eksempel 1:
[EnumMember()]
[OptionSetMetadata("Afventer_svar", Index=2, Color="#0000ff")]
Afventer_svar = 803750001,

Underscore bør være mellemrum.

Eksempel 2:
[EnumMember()]
[OptionSetMetadata("Ekstern_raadgiver", Index=2)]
Ekstern_raadgiver = 803750002,

aa bør være å.

Det er i seneste version (2.0.0) af XrmContext jeg har opdaget fejlen i.

**Comment by misoeli** [comment]
@pksorensen Just realized now this should be fixed in 2.0.2. Can you confirm?

**Comment by misoeli** [comment]
Closed - as mentioned, should be fixed in 2.0.2.
