### ISSUE TITLE
Missing enum name for global optionset with emojis as name

### ISSUE THREAD

**Issue by madsmai** [delegateas/XrmContext#48]
**Describe the bug**
When generating the context of a solution that contains a global optionset with emojis as names XrmContext sets no value in the name of the enum properties.

**To Reproduce**

Create a optionset and add values with emojis as the names
Run XrmContext

**Expected behavior**
Not quite sure what the names of these items should be - but something else than nothing

**Screenshots**
Optionset:
![image](https://user-images.githubusercontent.com/12827477/156755750-b0c387e4-dedb-4659-ab45-b1dc5f953c57.png)
Resulting enum
![image](https://user-images.githubusercontent.com/12827477/156755819-1fb8ff22-f7af-4eca-b77d-d72b164bda22.png)

**Environment**
- CRM/D365/CDS version: 9.2.22015.00128
- Tool version: 2.0.2
- Other applicable environments

**Additional context**
Contact me on teams(mem@delegate.dk) for more information if its not totally clear

**Comment by skovlund** [comment]
We generally scrape most unicode characters when generating typings. But we should have support for this though you need to specify the unicodes you want mapped.

I suggest you look into the `labelMappings` argument, documented [here](https://github.com/delegateas/XrmContext/wiki/Generate-Context#generation-arguments).

**Comment by madsmai** [comment]
That solved my issue, thanks
