### ISSUE TITLE
Deprecate possibility of generating context without specifying list of solutions

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmContext#5]
We have had a some issues (https://github.com/delegateas/XrmContext/issues/1, https://github.com/delegateas/XrmContext/issues/4) relating to generating the context when not specifying a list of solutions. 

In my view, it is clearly best practice to always work with solutions in CRM. This is standard part of CRM-development, as well as a prerequisite for having a deploy process.

When a solution has been specified, it is faster to generate the context, and the generated file is smaller. I thus see no reason to keep the functionality of being able to generate the context without specifying solutions. I suggest deprecating this in an upcoming release.

**Comment by Dremor** [comment]
In another hand, there is times when having the full context is useful, like if you want to provide a dll with a context to someone else, without having to rebuild the dll every time they start using a new entity.

#4 could be fixed by providing a blacklist of some sort, hardcoded, or as a new parameter.

**Comment by magesoe** [comment]
I can't see a use case where you would want all entities, since this is ~300 entities, where as you usually only modify ~80 of these. It's better to make a conscious choice about which entities you work with, rather than blindly generating contexts for all entities

**Comment by Dremor** [comment]
I understand (I started to use this approach too, but keeping as compatible as possible to CrmSvcUtils will help those who want to do the switch).

**Comment by mktange** [comment]
As an additional note:

XrmContext generates classes for ALL entities, including all system entities, even though you are not really able to interact with a lot of them.

CrmSvcUtil actually does some filtering when it generates a context for "all" entities (I can't remember what kind of filtering exactly). But it does not include most system entities, like XrmContext does.

**Comment by Dremor** [comment]
Maybe some sort of blacklist?

**Comment by magesoe** [comment]
We have decided to allow generating a context for all entities, but marking it as a bad-practice in the wiki - the reasons for this have been given in this discussion. I will mark this issue as closed.
