### ISSUE TITLE
Specifying the Namespace when generating context is ignored in the file "XrmExtentions.cs"

### ISSUE THREAD

**Issue by jacobblom** [delegateas/XrmContext#51]
![image](https://user-images.githubusercontent.com/12497236/172631924-20e1260c-c71e-4728-8165-a767bbcc966a.png)

**Comment by misoeli** [comment]
Fixed in 3.0.

**Comment by skovlund** [comment]
As @bo-stig-christensen has pointed out to me, this change has introduced an issue when using the tool to generate context for the standard table Entity ([documentation link](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/entity)).

Prior to this change this worked fine, as XrmExtensions.cs used its own namespace and all of its references to `Entity` resolved to `Microsoft.Xrm.Sdk.Entity`. But when this is placed in the same namespace as the generated context it will instead resolve to the `Entity` class generated for the above mentioned table. The resulting error is as circular reference (as `ExtendedEntity` inherits from `Entity` and vice versa). 

The simple fix seems to be to type the full name for all references to `Microsoft.Xrm.Sdk.Entity` in XrmExtensions.cs. However, this only resolves the naming in the context but may still be annoying for anyone writing code using both namespaces.

Alternative, we could choose to completely rename the generated `Entity` class to something like `_Entity`. I thought it might be easier to work with, but the more I think about it the more I lean towards the simple fix. I don't think it's worth the inconsistent naming, the additional development time, or the loss of backward compatibility for anyone already generating context for the table Entity.
