### ISSUE TITLE
GlobalOptionSets has a 'using DG.XrmContext'

### ISSUE THREAD

**Issue by remyvd** [delegateas/XrmContext#57]
After generating the C# context, the file GlobalOptionSets.cs as a using statement to DG.XrmContext.

This using statement fails the overal compilation of the code.

_Temp fix: I remove this statement._

See git-diff after re-generating the context:
![error](https://user-images.githubusercontent.com/8554104/189471493-9b6e6cac-fa28-4ee2-b8bc-b5ba28e5d68b.png)

**Comment by skovlund** [comment]
It seems that the upgrade to 3.0.0 (which moved XrmExtensions.cs to the user specified namespace instead of DG.XrmContext) has caused this error, as this using statement was overlooked. This should only be an issue when using the `onefile = "false"` argument.

**Comment by skovlund** [comment]
This should be fixed in 3.0.1

**Comment by RemyDuijkeren** [comment]
Thanks! I can validate that it works.
