### ISSUE TITLE
[Question] Cannot create/update entity on CRM using generated entities.

### ISSUE THREAD

**Issue by Dremor** [delegateas/XrmContext#6]
Hi,

I'm faced with yet another problem when using XrmContext : I can't send back the generated entities to the CRM (via the webservice). Is there something to do before sending the back ?

Best regards,

Dremor

**Comment by Dremor** [comment]
The problem seems to be that enums are send as their value label instead of the actual value. Example : I've create "new_test" on "opportunity",  with "Test1 = 168120000", "Test2 = 168120001" and "Test3 = 168120002" as OptionSet. Generation work fine, but when I send it back (using Microsoft.Xrm.Tooling.Connector.CrmServiceClient), instead of sending the integer value "168120000", it send "Test1" .

**Comment by henrikhannemose** [comment]
I am not sure I follow. Are you using the enums we generate for your optionsets? How are you setting the optionset values using these enums?

Can you upload a [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by Dremor** [comment]
Looks like a random problem on my side, asked a friend to help me, by the time he came to see the bug, it was gone.
