### ISSUE TITLE
Remove EntityReferenceName-fields from the generated context

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmContext#7]
Today we generate two fields per EntityReference:

- EntityReference (e.g. ParentAccountId)
- EntityReferenceName (e.g. ParentAccountIdName)

![ParentAccountIdName](https://user-images.githubusercontent.com/1955579/31122755-59a2e73e-a83d-11e7-8415-bf57d12895e0.png)

As far as I can see, the *Name fields are always null when fetched with QueryExpression. They are filled out when fetched via FetchXML (but I do not see that as a real use case when using XrmContext). 
We currently generate these fields since CrmSvcUtil generates them. I suggest removing the *Name fields, since it causes confusion for new developers (who think they can actually use them).

**Comment by Tolini** [comment]
Fixed in 8656192333159643b30e15f30c29cd375af39039
