### ISSUE TITLE
Ordering of properties in generated file(s)

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmContext#8]
When looking at a diff of the generated context before and after making changes in CRM, it appears that some properties are moved around in the generated file. What determines the ordering today?

Can we make it such that entities and generated properties for these entities are ordered in a deterministic way, e.g. alphabetically?

**Comment by Tolini** [comment]
Fixed in 536722eec92e4ba49b241a85fb2ec75a9afcba46
