### ISSUE TITLE
Add support for multi-select option sets in D365 9.0

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmContext#9]
In the July update for Dynamics 365 [multi-select option sets](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/new-in-july-2017-update-for-developers#new-attribute-type-multi-select-option-set) have been introduced. It appears that they have been implemented as an array of enum-values:

> Multi-select option sets supports all the client APIs supported for the option sets attributes and controls; the only difference is that the return value of certain methods will be an array instead of a single value.

Add support to XrmContext for this new data type.

A corresponding [issue ](https://github.com/delegateas/XrmDefinitelyTyped/issues/28) has been created for XrmDefinitelyTyped.

**Comment by magesoe** [comment]
Added in version 1.5.3
